music_tracks/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tracks.urls'), name='music-tracks'),
]

tracks/urls.py
from django.conf.urls import url

from . import views

app_name = 'Track'
urlpatterns = [
	# music track listing
    url(r'^tracks/$', views.track_list, name='track_list'),
    # track details
    url(r'^track/(?P<track_id>[0-9]+)/$', views.track_detail, name='track_detail'),
    # genre listing
    url(r'^genres/$', views.genre_list, name='genre_list'),
    # genre detail
    url(r'^genre/(?P<genres_id>[0-9]+)/$', views.genre_detail, name='genre_detail'),
    # add track
    url(r'^track/add/$', views.add_track, name='tracks-add'),
    # add genre
    url(r'^genre/add/$', views.add_genres, name='genres-add'),
    # edit track
    url(r'^track/(?P<pk>[0-9]+)/edit/$', views.add_track, name='tracks-edit'),
]

tracks/models.py
from django.db import models


class Genres(models.Model):
    """Model to store all genres"""
    genre = models.CharField(max_length=30, unique=True, blank=False)

    def __str__(self):
        return self.genre


class Track(models.Model):
    """Model to store track of music (Took assumtion that title won't
    be bigger then 200 chars)"""
    title = models.CharField(max_length=200, unique=True, blank=False)
    genre = models.ForeignKey(Genres, on_delete=models.CASCADE,
                              related_name='track')
    rating = models.IntegerField()

    def __str__(self):
        return self.title

tracks/forms.py
from django import forms
from .models import Track, Genres


class GenresForm(forms.ModelForm):
    """Form for genre"""

    class Meta:
        model = Genres
        fields = ['genre']


class TrackForm(forms.ModelForm):
    """Form to add a track"""
    
    class Meta:
        model = Track
        fields = ['title', 'genre', 'rating']
    # Customized the rating field so that one can add only 5,4 .. 1 only
    RATING_CHOICES = ((5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'))
    rating = forms.TypedChoiceField(choices=RATING_CHOICES,
                                    widget=forms.RadioSelect, coerce=int)

tracks/views.py
from django import forms
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Q
from .models import Track, Genres
from .forms import TrackForm, GenresForm


def track_list(request):
    """View to search on the basis of either music title or genre.
    If no filter is provided it return all tracks."""
    search_word = request.GET.get('search_box')
    if search_word:
        # Query to find all tracks which satisfy the above search term
        track_list = Track.objects.filter(Q(title__icontains=search_word) |
                                          Q(genre__genre__icontains=search_word))
    else:
        track_list = Track.objects.all()
    # Pagination tool to show only 10 tracks per page
    paginator = Paginator(track_list, 10)
    page = request.GET.get('page')
    try:
        tracks = paginator.page(page)
    except PageNotAnInteger:
        tracks = paginator.page(1)
    except EmptyPage:
        tracks = paginator.page(paginator.num_pages)
    context = {'track_list': tracks}
    return render(request, 'tracks/track_list.html', context)


def track_detail(request, track_id):
    """View to return the individual track details"""
    track = get_object_or_404(Track, pk=track_id)
    return render(request, 'tracks/track_detail.html', {'track': track})


def add_track(request, pk=None):
    """View to add and edit any track"""
    try:
        instance = Track.objects.get(pk=pk)
    except Track.DoesNotExist:
        # if track is added for first time we add it to db.
        form = TrackForm(request.POST)
    else:
        # if app is already exist we edit that
        form = TrackForm(request.POST or None, instance=instance)
    # If requsted to edit
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect('Track:track_detail', track_id=instance.pk)
    return render(request, "tracks/track_form.html", {'form': form})


def genre_list(request):
    """View to list all genre and paginated for 10 page per page."""
    genre_list = Genres.objects.all()
    paginator = Paginator(genre_list, 10)
    page = request.GET.get('page')
    try:
        genres = paginator.page(page)
    except PageNotAnInteger:
        genres = paginator.page(1)
    except EmptyPage:
        genres = paginator.page(paginator.num_pages)
    context = {'genre_list': genres}
    return render(request, 'genres/genre_list.html', context)


def genre_detail(request, genres_id):
    """View to return an individual genre detail with all music tracks of it."""
    genres = get_object_or_404(Genres, pk=genres_id)
    return render(request, 'genres/genre_detail.html', {'genre': genres.genre,
                                                        'genre_track': genres.track.all()})


def add_genres(request):
    """View to add and edit any genre."""
    if request.method == 'POST':
        form = GenresForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('Track:genre_list')
    else:
        form = GenresForm
        
    return render(request, 'genres/genre_form.html', {'form': form})

tracks/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}GreedyMusic{% endblock %}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
	<div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="{% url 'Track:track_list' %}">Home</a></li>
            <li role="presentation"><a href="{% url 'Track:genre_list' %}">Genre</a></li>
            <!-- <li role="presentation"><a href="#">Contact</a></li> -->
          </ul>
        </nav>
        <h3 class="text-muted"><a href="{% url 'Track:track_list' %}">Greedy Music</a></h3>
      </div>
      <br>
	      {% block content %}
	      {% endblock %}
      </div>
      <br><br>
      <footer class="footer">
        <p>&copy; 2017 GreedyMusic, Inc.</p>
      </footer>

    </div>

</body>
<script>
    $.fn.stars = function() {
        return $(this).each(function() {

            var rating = $(this).data("rating");

            var numStars = $(this).data("numStars");

            var fullStar = new Array(Math.floor(rating + 1)).join('<i class="fa fa-star"></i>');

            var halfStar = ((rating%1) !== 0) ? '<i class="fa fa-star-half-empty"></i>': '';

            var noStar = new Array(Math.floor(numStars + 1 - rating)).join('<i class="fa fa-star-o"></i>');

            $(this).html(fullStar + halfStar + noStar);

        });
    }

    $('.stars').stars();
</script>
</html>

tracks/templates/genres/genre_detail.html
{% extends 'base.html' %}

{% block content %}
	
	<div class="page-header">
	  <div class="row">
	    <h1>
		    <div class="col-xs-12 col-sm-6 col-md-8">
		  		{{ genre }}
		    </div>
		    <div class="col-xs-6 col-md-4">
		     <a class="btn btn-default" href="{% url 'Track:genres-add' %}" role="button">Edit</a>
		    </div>
		</h1>
	  </div>
	  <br><br>
	  <div class="row">
	    <ul class="list-group">
	    {% for track in genre_track %}
	    	<li class="list-group-item">
			  	<span class="badge"><span class="stars" data-rating="{{ track.rating }}" data-num-stars="5" ></span></span>
			   	<a href="/track/{{ track.id }}/">{{ track.title }}</a>
		    </li>
	    {% endfor %}
	    </ul>
	</div>

	</div>
	
{% endblock %}

tracks/templates/genres/genre_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add Genre</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

tracks/templates/genres/genre_list.html
{% extends 'base.html' %}

{% block content %}

	{% if genre_list %}
	    <ul class="list-group">
	    {% for genre in genre_list %}
	        <a href="/genre/{{ genre.id }}/">
	        	<li class="list-group-item">
			    	{{ genre.genre }}
		    	</li>
	        </a>
	    {% endfor %}
	    </ul>
	    <div class="pagination">
		    <span class="step-links">
		        {% if genre_list.has_previous %}
		            <a class="btn btn-default" href="?page={{ genre_list.previous_page_number }}">Previous</a>
		        {% endif %}

		        <span class="current">
		            Page {{ genre_list.number }} of {{ genre_list.paginator.num_pages }}.
		        </span>

		        {% if genre_list.has_next %}
		            <a class="btn btn-default" href="?page={{ genre_list.next_page_number }}">Next</a>
		        {% endif %}
		    </span>
		</div>
	{% else %}
	    <p>No genre are available.</p>
	{% endif %}
	<a class="btn btn-primary btn-lg btn-block" href="{% url 'Track:genres-add' %}" role="button">Add New Genre</a>
	
{% endblock %}

tracks/templates/tracks/track_detail.html
{% extends 'base.html' %}

{% block content %}
	
	<div class="page-header">
	  <div class="row">
	    <h1>
		    <div class="col-xs-12 col-sm-6 col-md-8">
		  		{{ track.title }}<br>
		  		<span class="badge"><span class="stars" data-rating="{{ track.rating }}" data-num-stars="5" ></span></span><br>
		  		<a href="/genre/{{ track.genre.id }}/">{{ track.genre.genre }}</a><br>
		    </div>
		    <div class="col-xs-6 col-md-4">
		     <a class="btn btn-default" href="{% url 'Track:tracks-edit' pk=track.pk %}" role="button">Edit</a>
		    </div>
		</h1>
	  </div>
	</div>
	
{% endblock %}

tracks/templates/tracks/track_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add music</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

tracks/templates/tracks/track_list.html
{% extends 'base.html' %}

{% block content %}
	{% if track_list %}
		<div class="row">
		<form type="get" class="form-horizontal" action="." style="margin: 0">
			<div class="form-group">
		    	<input  id="search_box" class="form-control" type="text" name="search_box" placeholder="Search Song Track by Title or Genre [ e.g. 'Shape of you' || 'pop / jazz / classical' ]" >
		    </div>
		    <div class="form-group">
		    	<button id="search_submit" class="btn btn-default center-block"  type="submit" >Submit</button>
		    </div>
		</form>
		</div>
		<div class="row">
		    <ul class="list-group">
		    {% for track in track_list %}
		    	<li class="list-group-item">
				 	<span class="badge"><span class="stars" data-rating="{{ track.rating }}" data-num-stars="5" ></span></span>
				   	<a href="/track/{{ track.id }}/">{{ track.title }}</a>
				   	<a href="/genre/{{ track.genre.id }}/">[{{ track.genre.genre }}]</a>
			    </li>
			{% endfor %}
		    </ul>
		    <div class="pagination">
			    <span class="step-links">
			        {% if track_list.has_previous %}
			            <a class="btn btn-default" href="?page={{ track_list.previous_page_number }}">Previous</a>
			        {% endif %}

			        <span class="current">
			            Page {{ track_list.number }} of {{ track_list.paginator.num_pages }}.
			        </span>

			        {% if track_list.has_next %}
			            <a class="btn btn-default" href="?page={{ track_list.next_page_number }}">Next</a>
			        {% endif %}
			    </span>
			</div>
		{% else %}
		    <p>No music tracks are available.</p>
		{% endif %}
		<a class="btn btn-primary btn-lg btn-block" href="{% url 'Track:tracks-add' %}" role="button">Add New Track</a>
	</div>
{% endblock %}